### ISSUE TITLE
Refactor frontend tooling

### ISSUE THREAD

**Issue by TineRobbe** [thedatahub/Datahub#15]
The installation of Bootstrap seems to be unnecessary. If so, it can be deleted from the composer.json file.

**Comment by netsensei** [comment]
Bootstrap is currently loaded via the [BraincraftBootsrapBundle](https://github.com/braincrafted/bootstrap-bundle). While this bundle has it merits, it's also very limited towards front end workflows (minifying, etc.)

Modern front end workflows aren't managed through PHP. They are managed through javascript tools such as [npm](https://www.npmjs.com/) or [yarn](https://yarnpkg.com). 

We should wire up a front end tooling with Encore per the [Symfony documentation](https://symfony.com/doc/current/frontend/encore/installation.html).

- [ ] Create a package.json file with webpack.config.js
- [ ] Move all custom JS in the workflow
- [ ] Move JS dependencies (JQuery, etc.) into the workflow
- [ ] Add Bootstrap via sass
- [ ] Move all custom CSS into the workflow (as Sass)
