### ISSUE TITLE
When an entity (user, client, token) is edited, a flash message should appear

### ISSUE THREAD

**Issue by netsensei** [thedatahub/Datahub#47]
## Detailed description

When editing or updating an entity as an administrator (user, client,...) you don't get a message if the edit wether or not the edit was successful. This leaves the administrator in the dark if things went as expected.

When a form is submitted, it should always show a proper flash message reporting whether an action went as expected.

## Context

Usability issue.

**Comment by Kitania** [comment]
Flash is considered unsafe and deprecated (and most browsers don't enable it on default), wouldn't it be better to use a Javascript popup message instead?

**Comment by netsensei** [comment]
Oh! I didn't mean "Flash, the technology". Flash message = Alert Message.

See: https://getbootstrap.com/docs/4.0/components/alerts/

Flash = popup message that appears after action and disappears after 5 seconds.

**Comment by Kitania** [comment]
Oh, that kind of flash.

**Comment by netsensei** [comment]
This issue is an general problem. I'm going to close this and revisit it in more specific / concrete issues / use cases. See #66 and it's sub issues to get the idea.
